[project]
name = "angular14-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.118.0",
    "openpyxl>=3.1.5",
    "pydantic>=2.11.9",
    "python-multipart>=0.0.20",
    "uvicorn[standard]>=0.37.0",
]
